# EDA & DATA Dictionary

In [1]:
import os
import pandas as pd

In [2]:
project_root = os.path.dirname(os.getcwd())

raw_data_path = os.path.join(project_root, "data", "raw_online_retail_II.csv")

raw_data_path

's:\\Projects\\online-retail-ii\\data\\raw_online_retail_II.csv'

In [3]:
raw_df = pd.read_csv(raw_data_path)

print(f"[+] Loaded Dataset shape: {raw_df.shape[0]:,} rows and {raw_df.shape[1]} columns")

[+] Loaded Dataset shape: 525,461 rows and 8 columns

In [4]:
raw_df.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom

In [5]:
print("="*50)
print("1. STRUCTURAL DATA TYPES & NULLS")
print("="*50)
raw_df.info()

==================================================
1. STRUCTURAL DATA TYPES & NULLS
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  object
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 32.1+ MB

In [6]:
print("="*50)
print("2. SUMMARY STATISTICS")
print("="*50)
display(raw_df.describe().T)

==================================================
2. SUMMARY STATISTICS
==================================================

,count,mean,std,min,25%,50%,75%,max
Quantity,525461.0,10.337667,107.424110,-9600.00,1.00,3.0,10.00,19152.00
Price,525461.0,4.688834,146.126914,-53594.36,1.25,2.1,4.21,25111.09
Customer ID,417534.0,15360.645478,1680.811316,12346.00,13983.00,15311.0,16799.00,18287.00

In [34]:
# Business Definitions for Each Column
# The Below dictionary has the following format
# |Label|Units|Definition|
business_definitions = {
    "Invoice": ("Invoice", "Transaction ID","Invoice number. Nominal, 6 to 7 characters in length, starting with '4', '5', 'C', or 'A'. Standard transactions begin with '4' or '5', 'C' indicates cancellations, and 'A' indicates adjustment records."),
    "StockCode": ("Stock Code", "Product ID", "Product or administrative item code. Nominal, 1 to 12 characters in length. Primarily consists of 5-digit numeric SKUs, but also includes alphanumeric variants, short operational/discount flags (e.g., 'D', 'M', 'S', 'B'), shipping and handling codes (e.g., 'POST', 'DOT'), test strings, and descriptive financial entries or vouchers (e.g., 'BANK CHARGES', 'gift_0001_80')."),
    "Description": ("Description", "Text", "Product or administrative item name. Nominal text field. Contains descriptive text for products, operational fees, or vouchers. Exhibits 2,928 missing records across 1,920 unique stock codes, of which 2,563 are recoverable via SKU cross-referencing. Also contains operational status anomalies and warehouse noise ('found', 'missing', 'damaged', '?') requiring filtering prior to imputation."),
    "Quantity": ("Quantity", "Count", "The quantities of each product (item) per transaction. Numeric."),
    "InvoiceDate": ("Invoice Date", "Date", "Invoice Date and time. Numeric, the day and time when each transaction was generated."),
    "Price": ("Unit Price", "Currency Sterling", "Unit price. Numeric, Product price per unit in sterling."),
    "Customer ID": ("Customer ID", "Customer ID", "Customer number. Nominal, a 5-digit integral number uniquely assigned to each customer."),
    "Country": ("Country", "Text", "Country name. Nominal, the name of the country where each customer resides.")
}

In [35]:
# |Feature Name|Business Label|Data Type|unit|Null count|Unique values|Description|
dict_list = []

for col in raw_df.columns:
    label, unit, definition = business_definitions.get(col, (col, "N/A", "No Definition"))
    dict_list.append({
        "Feature Name": col,
        "Business Label": label,
        "Data Type": str(raw_df[col].dtype),
        "Unit": unit,
        "Null Count": raw_df[col].isnull().sum(),
        "Unique Values": raw_df[col].nunique(),
        "Description": definition
    })

dict_df = pd.DataFrame(dict_list)
display(dict_df)

,Feature Name,Business Label,Data Type,Unit,Null Count,Unique Values,Description
0,Invoice,Invoice,object,Transaction ID,0,28816,"Invoice number. Nominal, 6 to 7 characters in ..."
1,StockCode,Stock Code,object,Product ID,0,4632,"Product or administrative item code. Nominal, ..."
2,Description,Description,object,Text,2928,4681,Product or administrative item name. Nominal t...
3,Quantity,Quantity,int64,Count,0,825,The quantities of each product (item) per tran...
4,InvoiceDate,Invoice Date,object,Date,0,25296,"Invoice Date and time. Numeric, the day and ti..."
5,Price,Unit Price,float64,Currency Sterling,0,1606,"Unit price. Numeric, Product price per unit in..."
6,Customer ID,Customer ID,float64,Customer ID,107927,4383,"Customer number. Nominal, a 5-digit integral n..."
7,Country,Country,object,Text,0,40,"Country name. Nominal, the name of the country..."

In [9]:
## audit for invoice column
print(f"Unique values in Invoice column: {raw_df['Invoice'].unique().shape[0]}")
print(f"Null values in Invoice column: {raw_df['Invoice'].isnull().sum()}")

c_count = raw_df.query('Invoice.str.startswith("C")', engine='python').shape[0]
print(f"Records that are starting with c: {c_count}")

unique_c_count = raw_df.query('Invoice.str.startswith("C")', engine='python')["Invoice"].unique().shape[0]
print(f"Unique Records of cancellations: {unique_c_count}")

print(f"Invoice ID entries start with: {set([i[0] for i in raw_df['Invoice'].unique()])}")

print(f"Length of the entries are: {set([len(i) for i in raw_df['Invoice'].unique()])}")

Unique values in Invoice column: 28816
Null values in Invoice column: 0
Records that are starting with c: 10206
Unique Records of cancellations: 4592
Invoice ID entries start with: {'A', '4', 'C', '5'}
Length of the entries are: {6, 7}

In [10]:
## audit for stockcode column
print(f"Unique values in stockcode column: {raw_df['StockCode'].unique().shape[0]}")
print(f"Null values in stockcode column: {raw_df['StockCode'].isnull().sum()}")
print(f"Stock Code starts with the following: {set([i[0] for i in raw_df['StockCode'].unique()])}")
print(f"Stock Code length ranges from: {set([len(i) for i in raw_df['StockCode'].unique()])}")

len_dic = {str(l): len(raw_df['StockCode'][raw_df['StockCode'].str.len() == l]) for l in set([len(i) for i in raw_df['StockCode'].unique()])}

print(f"Dictionary representing the number of entires for each length in Stock Code: {len_dic}")

for l in set([len(i) for i in raw_df['StockCode'].unique()]):
    print(str(l), raw_df.query(f'StockCode.str.len() == {l}', engine='python')['StockCode'].unique())

Unique values in stockcode column: 4632
Null values in stockcode column: 0
Stock Code starts with the following: {'M', 'P', 'T', 'm', 'C', '2', '1', '6', 'B', 'g', 'S', '4', '5', '8', 'D', 'G', '7', '9', 'A', '3'}
Stock Code length ranges from: {1, 2, 3, 4, 5, 6, 7, 8, 9, 12}
Dictionary representing the number of entires for each length in Stock Code: {'1': 998, '2': 139, '3': 736, '4': 881, '5': 445349, '6': 76102, '7': 1003, '8': 96, '9': 26, '12': 131}
1 ['D' 'M' 'm' 'S' 'B']
2 ['C2' 'C3']
3 ['DOT']
4 ['POST' 'PADS' 'GIFT']
5 ['85048' '22041' '21232' ... '22935' '22933' '21120']
6 ['79323P' '79323W' '48173C' ... '85049g' '72803b' '79151B']
7 ['79323LP' '15056BL' '79323GR' '15056bl' 'TEST001' 'TEST002' '72024HC'
 'ADJUST2' '47503J ']
8 ['DCGS0058' 'DCGS0068' 'DCGS0004' 'DCGS0076' 'DCGS0003' 'DCGS0072'
 'DCGS0044' 'DCGS0006' 'DCGS0016' 'DCGS0027' 'DCGS0036' 'DCGS0039'
 'DCGS0060' 'DCGS0056' 'DCGS0059' 'DCGSLBOY' 'DCGS0053' 'DCGS0062'
 'DCGS0037' 'DCGSSBOY' 'DCGS0069' 'DCGS0070' 'DCGS0075' 'DCGS0041']
9 ['DCGS0066N' 'DCGSSGIRL' 'DCGSLGIRL' 'AMAZONFEE']
12 ['BANK CHARGES' 'gift_0001_80' 'gift_0001_20' 'gift_0001_10'
 'gift_0001_50' 'gift_0001_30' 'gift_0001_40' 'gift_0001_60'
 'gift_0001_70' 'gift_0001_90']

In [11]:
# audit for description column

print(f"Unique values in Description column: {raw_df['Description'].unique().shape[0]}")
print(f"Null values in Description column: {raw_df['Description'].isnull().sum()}")

Unique values in Description column: 4682
Null values in Description column: 2928

In [13]:
raw_df[raw_df['Description'].str.strip() == ''].shape[0]

0

In [14]:
# continue from refilling the missing description values